//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogDiabetes.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diabetes_Log
    {
        public int ID { get; set; }
        public System.DateTime Date_Time { get; set; }
        public string BK_Lunch_Dinner_Snack { get; set; }
        public int Glucose_Number { get; set; }
    }
}
