//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogDiabetes.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Diabetes
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Before_Meal_Test { get; set; }
        public string Meal_BK_L_D_S { get; set; }
        public string What_Was_Eaten { get; set; }
        public string Hours_After_Meal_Test { get; set; }
    }
}
